baseURL = 'https://devdrshn.github.io/'
languageCode = 'en-us'
title = 'Dev Drshn'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  
  # This section creates the "Profile Mode" on the homepage
  [params.profileMode]
    enabled = true
    title = "Dev Darshan"
    subtitle = "Engineering Student | Electronics"
    imageUrl = "https://github.com/devdrshn.png" # This automatically pulls your GitHub profile pic
    imageTitle = "My Profile"
    imageWidth = 150
    imageHeight = 150
    
    [[params.profileMode.buttons]]
      name = "Posts"
      url = "/posts"
    
    [[params.profileMode.buttons]]
      name = "Events"
      url = "/events"

    [[params.socialIcons]]
      name = "github"
      url = "https://github.com/devdrshn"

    [[params.socialIcons]]
      name = "linkedin"
      url = "https://www.linkedin.com/in/dev-darshan-s-b28b81363/"  # Update this!